### ISSUE TITLE
你好！有没有详细安装教程呢！这是一个非常不错的源码

### ISSUE THREAD

**Issue by yanyuol** [qxchuckle/paste-share-server#1]
你好！有没有详细安装教程呢！这是一个非常不错的源码

**Comment by qxchuckle** [comment]
之前写的，有空我加到readme里

![image](https://github.com/qxchuckle/paste-share-server/assets/55614189/c2f308f2-a824-4baf-b591-52109297c63a)

**Comment by qxchuckle** [comment]
vercel部署的话，分别添加前后端仓库，再分别配环境变量就行
![image](https://github.com/qxchuckle/paste-share-server/assets/55614189/195fdb6a-d45d-49db-9dbd-8227bbe184da)
